/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        // ─── Eco-Tech Palette ─────────────────────────────────────────────
        'eco-bg': '#0b1220',
        'eco-bg2': '#0d1a2e',
        'eco-surface': 'rgba(255,255,255,0.04)',
        'eco-surface2': 'rgba(255,255,255,0.08)',
        'eco-border': 'rgba(255,255,255,0.08)',
        'eco-text': '#e2f5f0',
        'eco-muted': '#7ab8a8',
        'eco-green': '#10b981',
        'eco-green2': '#34d399',
        'eco-cyan': '#06b6d4',
        'eco-teal': '#0d9488',
        'eco-accent': '#10b981',
        // Legacy eco-* tokens (keeps other pages working)
        'eco-accent2': '#8fffaa',
        'eco-accent-dim': '#0d2e1e',
        'eco-surface3': '#182018',
        'eco-danger': '#ff5252',
        'eco-warn': '#ffca28',
        // SaaS tokens (prev version still used by other pages)
        'saas-bg': 'var(--saas-bg)',
        'saas-bg2': 'var(--saas-bg2)',
        'saas-surface': 'var(--saas-surface)',
        'saas-surface2': 'var(--saas-surface2)',
        'saas-border': 'var(--saas-border)',
        'saas-text': 'var(--saas-text)',
        'saas-muted': 'var(--saas-muted)',
        'saas-blue': '#6366f1',
        'saas-purple': '#8b5cf6',
        'saas-cyan': '#22d3ee',
        'saas-green': '#4ade80',
      },
      fontFamily: {
        'syne': ['Syne', 'sans-serif'],
        'dm': ['DM Sans', 'sans-serif'],
        'inter': ['Inter', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        '3xl': '1.5rem',
        '2xl': '1rem',
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        glow: "0 0 30px -5px rgba(99, 102, 241, 0.5)",
        'glow-lg': "0 0 60px -10px rgba(99, 102, 241, 0.6)",
        'glow-green': "0 0 40px -8px rgba(16, 185, 129, 0.6)",
        'glow-cyan': "0 0 40px -8px rgba(6, 182, 212, 0.5)",
        'glow-teal': "0 0 30px -6px rgba(13, 148, 136, 0.5)",
        glass: "0 8px 32px 0 rgba(0,0,0,0.37), inset 0 1px 0 rgba(255,255,255,0.1)",
        'glass-hover': "0 16px 48px 0 rgba(0,0,0,0.4), inset 0 1px 0 rgba(255,255,255,0.15), 0 0 30px rgba(16,185,129,0.15)",
        card: "0 4px 24px rgba(0,0,0,0.25)",
        'card-hover': "0 12px 40px rgba(16,185,129,0.15)",
      },
      backgroundImage: {
        'gradient-eco': 'linear-gradient(135deg, #10b981 0%, #06b6d4 50%, #0d9488 100%)',
        'gradient-eco-btn': 'linear-gradient(135deg, #059669 0%, #0891b2 100%)',
        'gradient-hero': 'linear-gradient(135deg, #0b1220 0%, #0d1a2e 50%, #071520 100%)',
        'gradient-glow': 'radial-gradient(ellipse at 50% 0%, rgba(16,185,129,0.15) 0%, transparent 70%)',
        'gradient-card': 'linear-gradient(135deg, rgba(16,185,129,0.06) 0%, rgba(6,182,212,0.04) 100%)',
        'gradient-primary': 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)',
        'gradient-green': 'linear-gradient(135deg, #4ade80 0%, #22d3ee 100%)',
        'radial-glow': 'radial-gradient(circle at center, rgba(99,102,241,0.15) 0%, transparent 70%)',
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "caret-blink": { "0%,70%,100%": { opacity: "1" }, "20%,50%": { opacity: "0" } },
        "float": {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-12px)" },
        },
        "float-slow": {
          "0%, 100%": { transform: "translateY(0px) rotate(0deg)" },
          "50%": { transform: "translateY(-8px) rotate(1deg)" },
        },
        "wave": {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
        "wave2": {
          "0%": { transform: "translateX(0) scaleY(1)" },
          "50%": { transform: "translateX(-25%) scaleY(0.85)" },
          "100%": { transform: "translateX(-50%) scaleY(1)" },
        },
        "pulse-glow-green": {
          "0%, 100%": { boxShadow: "0 0 20px rgba(16,185,129,0.3)" },
          "50%": { boxShadow: "0 0 50px rgba(16,185,129,0.6), 0 0 80px rgba(16,185,129,0.2)" },
        },
        "gradient-shift": {
          "0%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
          "100%": { backgroundPosition: "0% 50%" },
        },
        "orb-drift": {
          "0%, 100%": { transform: "translate(0,0) scale(1)" },
          "33%": { transform: "translate(40px,-30px) scale(1.08)" },
          "66%": { transform: "translate(-25px,15px) scale(0.95)" },
        },
        "scan-line": {
          "0%": { transform: "translateY(-100%)", opacity: "0.5" },
          "100%": { transform: "translateY(100vh)", opacity: "0" },
        },
        "shimmer": {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "spin-slow": {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(24px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "float": "float 4s ease-in-out infinite",
        "float-slow": "float-slow 7s ease-in-out infinite",
        "wave": "wave 12s linear infinite",
        "wave2": "wave2 16s ease-in-out infinite",
        "pulse-glow-green": "pulse-glow-green 3s ease-in-out infinite",
        "gradient-shift": "gradient-shift 8s ease-in-out infinite",
        "orb-drift": "orb-drift 15s ease-in-out infinite",
        "scan-line": "scan-line 6s linear infinite",
        "shimmer": "shimmer 2s linear infinite",
        "spin-slow": "spin-slow 12s linear infinite",
        "fade-in-up": "fade-in-up 0.6s ease-out forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
